### ISSUE TITLE
images-for-object-detection

### ISSUE THREAD

**Issue by jason9865** [DI-LEE/crop-disease-diagnosis-service#18]
![label8](https://user-images.githubusercontent.com/31498000/187653219-083cef9d-f4db-4e69-9a1b-755228aa0d75.jpg)

![label9](https://user-images.githubusercontent.com/31498000/187653281-6f922bc7-37f8-46f6-9f29-ef55051d61d4.jpg)

**Comment by DI-LEE** [comment]
thanks bro
